version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/save"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    commit-message:
      prefix: "fix"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/restore"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    commit-message:
      prefix: "fix"
      include: "scope"
