name: 'job-root-cache/cleanup'

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      # Remove the cache of the root directory
      - name: clear cache
        if: ${{ always() }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git init --bare
          gh extension install actions/gh-actions-cache
          gh actions-cache delete job-setup-cache-${{ github.run_id }}-${{ runner.os }} --confirm
